In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn .model_selection import train_test_split
import joblib

In [20]:
df=pd.read_csv("diabetes.csv")

In [21]:
df.shape

(2000, 9)

In [22]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [23]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

In [25]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,3.703500,121.182500,69.145500,20.935000,80.254000,32.193000,0.470930,33.090500,0.342000
std,3.306063,32.068636,19.188315,16.103243,111.180534,8.149901,0.323553,11.786423,0.474498
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,63.500000,0.000000,0.000000,27.375000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,40.000000,32.300000,0.376000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,32.000000,130.000000,36.800000,0.624000,40.000000,1.000000
max,17.000000,199.000000,122.000000,110.000000,744.000000,80.600000,2.420000,81.000000,1.000000

In [26]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [27]:
X=df[["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]]
y=df["Outcome"]

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [30]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test_Scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7625
[[196  57]
 [ 38 109]]
              precision    recall  f1-score   support

           0       0.84      0.77      0.80       253
           1       0.66      0.74      0.70       147

    accuracy                           0.76       400
   macro avg       0.75      0.76      0.75       400
weighted avg       0.77      0.76      0.77       400

In [ ]:
# from sklearn .preprocessing import StandardScaler

# scaler = StandardScaler()

# X_train_Scaled = scaler.fit_transform(X_train)
# X_test_Scaled = scaler.transform(X_test)

In [ ]:
# from sklearn .linear_model import LogisticRegression

In [ ]:
# model=LogisticRegression(max_iter=2000)
# model = LogisticRegression(class_weight="balanced")
# model.fit(X_train_Scaled,y_train)

LogisticRegression(class_weight='balanced')

In [ ]:
# accuracy =model.score(X_train_Scaled,y_train)
# print(f"Model Accuracy:{accuracy * 100:.2f}%")

Model Accuracy:75.44%

In [ ]:
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# y_pred = model.predict(X_test_Scaled)

# print("Accuracy:", accuracy_score(y_test, y_pred))
# print(confusion_matrix(y_test, y_pred))
# print(classification_report(y_test, y_pred))

Accuracy: 0.7625
[[196  57]
 [ 38 109]]
              precision    recall  f1-score   support

           0       0.84      0.77      0.80       253
           1       0.66      0.74      0.70       147

    accuracy                           0.76       400
   macro avg       0.75      0.76      0.75       400
weighted avg       0.77      0.76      0.77       400

In [33]:
pipe.fit(X_train, y_train)          
joblib.dump(pipe, "diabetes.pkl")

['diabetes.pkl']

In [ ]:
# #decision tree
# from sklearn.tree import DecisionTreeClassifier
# dt = DecisionTreeClassifier(random_state=42)

# dt.fit(X_train_Scaled, y_train)
# y_pred = dt.predict(X_test_Scaled)
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# print("Accuracy:", accuracy_score(y_test, y_pred))
# print(confusion_matrix(y_test, y_pred))
# print(classification_report(y_test, y_pred))

Accuracy: 0.98
[[245   8]
 [  0 147]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       253
           1       0.95      1.00      0.97       147

    accuracy                           0.98       400
   macro avg       0.97      0.98      0.98       400
weighted avg       0.98      0.98      0.98       400